# Generated by Django 3.1.5 on 2021-01-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0002_listtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListTable',
        ),
    ]
