# Generated by Django 3.1.5 on 2021-01-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0004_listtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestable',
            name='salesDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
