# Generated by Django 3.1.5 on 2021-01-29 06:06

import apis1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0006_auto_20210129_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestable',
            name='salesDate',
            field=models.DateField(validators=[apis1.models.SalesTable.validate_salesDate]),
        ),
    ]
