# Generated by Django 3.1.5 on 2021-01-29 06:23

import apis1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0007_auto_20210129_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetable',
            name='purchaseDate',
            field=models.DateField(validators=[apis1.models.PurchaseTable.validate_purchaseDate]),
        ),
    ]
