# Generated by Django 3.1.5 on 2021-02-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0008_auto_20210129_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisitionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseItem', models.CharField(max_length=20)),
                ('purchaseAmount', models.FloatField()),
                ('purchaseDate', models.DateField()),
                ('vendorName', models.CharField(max_length=30)),
                ('unitPrice', models.FloatField()),
                ('phoneNo', models.IntegerField()),
                ('approve', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
