# Generated by Django 3.1.5 on 2021-02-12 10:31

import apis1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0010_auto_20210212_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisitiontable',
            name='approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitiontable',
            name='phoneNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitiontable',
            name='purchaseAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitiontable',
            name='purchaseDate',
            field=models.DateField(blank=True, null=True, validators=[apis1.models.PurchaseRequisitionTable.validate_PA_Date]),
        ),
        migrations.AlterField(
            model_name='purchaserequisitiontable',
            name='purchaseItem',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitiontable',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitiontable',
            name='unitPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitiontable',
            name='vendorName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
