# Generated by Django 3.1.5 on 2021-02-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0013_auto_20210215_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseRequisitionTableAcceptReject',
        ),
    ]
