# Generated by Django 3.1.5 on 2021-02-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0014_delete_purchaserequisitiontableacceptreject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept_Reject_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk', to='apis1.purchaserequisitiontable')),
            ],
        ),
    ]
