# Generated by Django 3.1.5 on 2021-02-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis1', '0015_accept_reject_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept_reject_table',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='apis1.purchaserequisitiontable'),
        ),
    ]
