# Generated by Django 3.1.5 on 2021-01-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_item', models.CharField(max_length=30)),
                ('sales_amount', models.CharField(max_length=10)),
                ('sales_date', models.CharField(max_length=10)),
            ],
        ),
    ]
