# Generated by Django 3.1.5 on 2021-01-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_item', models.CharField(max_length=30)),
                ('purchase_amount', models.CharField(max_length=10)),
                ('purchase_date', models.CharField(max_length=10)),
            ],
        ),
    ]
