# Generated by Django 3.1.5 on 2021-01-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_purchase_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_table',
            name='sales_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
