# Generated by Django 3.1.5 on 2021-01-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_sales_table_sales_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_table',
            name='sales_datetime',
        ),
    ]
