# Generated by Django 3.1.5 on 2021-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20210111_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_table',
            name='purchase_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase_table',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sales_table',
            name='sales_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales_table',
            name='sales_date',
            field=models.DateField(),
        ),
    ]
